### PR TITLE
FIX: Allow IndexedGzipFile to be deepcopied

### PR DESCRIPTION
**Pull request by effigies**
Starting with a test to trigger your CI, since I'm not set up to build and test locally.

Inspired by https://github.com/nipy/nibabel/issues/969

### CODE REVIEW

**Comment by effigies** [comment]
Ah, looks like your CI doesn't trigger. Will send along my proposed fix. I'll see if I can test on a Linux box shortly.

**Comment by pauldmccarthy** [comment]
Hi @effigies, it turns out that this is a bug which affects both pickling and copying.  My `test_is_picklable` unit test is slightly broken, and didn't catch the `BytesIO.mode` error.

In the formation of my unit test:

```
        gzf        = igzip.IndexedGzipFile(fname)
        first50MB  = gzf.read(1048576 * 50)
        pickled    = pickle.dumps(gzf)
        second50MB = gzf.read(1048576 * 50)
```

I had forgotten that the seek point index is only populated on calls to `.seek`, *not* on calls to `.read`. So after the first read, the index is still empty, so the `__reduce__` method does not call `export_index`, and the bug isn't uncovered. If I change the test to:

```
        gzf        = igzip.IndexedGzipFile(fname)
        first50MB  = gzf.read(1048576 * 50)
        gzf.seek(gzf.tell())
        pickled    = pickle.dumps(gzf)
        second50MB = gzf.read(1048576 * 50)
```

then the test fails in the same way as reported at [neurostuff/NiMARE](https://github.com/neurostuff/NiMARE/issues/399#issuecomment-729152173).

Your patch solves the `BytesIO.mode` problem, but there is another problem, in the fact that a `BytesIO` object does not have a `fileno()` method (because it is not associated with a file), and therefore the subsequent [`fd  = fdopen(fileobj.fileno(), 'ab')`](https://github.com/pauldmccarthy/indexed_gzip/blob/96fdfe7dd558496d737f6b18d25881093d9d9191/indexed_gzip/indexed_gzip.pyx#L742) line fails.

I could have sworn that I looked into this, and formed the impression that I could trick the `zran.c:zran_export_index` function to save to an in-memory buffer. But I can't find any evidence of this, so I think the best option is to change `IndexedGzipFile.__reduce__` so that it uses a temporary file, instead of an `io.BytesIO` object. Any thoughts?

**Comment by pauldmccarthy** [comment]
Oh, I also meant to ask you about your comment in the test case: `# IndexedGzipFile should be copyable whether it retains or drops filehandles`.

I am fairly certain (although not 100%) that an open file handle cannot be pickled/copied, and figured that copying file descriptors was just a bad idea, which is why I [included a guard](https://github.com/pauldmccarthy/indexed_gzip/blob/96fdfe7dd558496d737f6b18d25881093d9d9191/indexed_gzip/indexed_gzip.pyx#L945-L949) to prevent copies in this situation. I'm happy to hear differing opinions if you have any though.

**Comment by effigies** [comment]
You're definitely right about it being unsafe to share open filehandles. I've fixed up the test.

> I could have sworn that I looked into this, and formed the impression that I could trick the `zran.c:zran_export_index` function to save to an in-memory buffer. But I can't find any evidence of this, so I think the best option is to change `IndexedGzipFile.__reduce__` so that it uses a temporary file, instead of an `io.BytesIO` object. Any thoughts?

I think the only alternative is to create an alternative serialization/deserialization for indices for use in this case. In the short term, a temporary file makes sense, and hopefully most people's environments are set up to create tempfiles on a ramdisk.



> I am fairly certain (although not 100%) that an open file handle cannot be pickled/copied, and figured that copying file descriptors was just a bad idea, which is why I [included a guard](https://github.com/pauldmccarthy/indexed_gzip/blob/96fdfe7dd558496d737f6b18d25881093d9d9191/indexed_gzip/indexed_gzip.pyx#L945-L949) to prevent copies in this situation. I'm happy to hear differing opinions if you have any though.

I think you're right. For some reason I assumed open filehandles could be copied, but as I've dug into this, I've become convinced otherwise.

**Comment by pauldmccarthy** [comment]
I've already started playing with this, so am happy to make a second pass, if I could ask for your eyes on it when it's ready?

**Comment by effigies** [comment]
Yup, sounds good. I'll go ahead and push my latest changes here for reference, but happy to leave the hard work to you. :-)

**Comment by effigies** [comment]
Yup. GH actions is pretty manageable, and pleasantly multi-os. On nibabel I abstracted most steps out so future migrations should be easier, if you need a model.

**Comment by pauldmccarthy** [comment]
Already looking through your implementation, thanks :) 

I might have to sit on this for a couple of days, but will have a new version out before xmas..

**Comment by pauldmccarthy** [comment]
This was merged as part of #51

**Comment by effigies** [comment]
Thanks, Paul!

**Pull request closed without merging**
